### ISSUE TITLE
Updating strings in the name table results in otf files that fail Macos system validation.

### ISSUE THREAD

**Issue by NoMoreNicksLeft** [silnrsi/font-ttf#1]
Code with the following form fails silently with no hint of the problem:

    my $font = Font::TTF::Font->open($ARGV[0]) || die ("Couldn't open TTF '$ARGV[0]'\n");
    $font->{'name'}->read();

    # Need the pid (platform, eid(encoding), and lid (language).
    my @ids = $font->{'name'}->find_name(1);

    $font->{'name'}->set_name(16, "$family", $ids[3], @{[ [ $ids[1], $ids[2] ] ]});
    $font->{'name'}->set_name(17, "$subfamily", $ids[3], @{[ [ $ids[1], $ids[2] ] ]});

    $font->update();

    $font->out($save);

This works if the input file is ttf, but otf files result in a "failed system validation" in Font Book. The output file is roughly the same size as the original. Using Data::Dumper shows that the data structures look similar in before and after. It's not clear if this module supports an older version of otf and my files to test with are a newer, incompatible version. Or if otf is just supported as a read-only format.

**Comment by bobh0303** [comment]
First of all, the code should be something more like:
```
# Need the pid (platform, eid(encoding), and lid (language).
my @cover = $font->{'name'}->pe_list();

$font->{'name'}->set_name(16, "$family", "en", @cover);
$font->{'name'}->set_name(17, "$subfamily", "en", @cover);
```
Notes:
- The 3rd parameter of `set_name()` is a language tag, not a numeric language ID.
- The `pe_list()` function delivers a list of all platform/encoding pairs already used in the font.

But even with that fixed, it doesn't [currently] work with CFF-flavored fonts. 

I have just pushed a change that will allow your use-case to work. If you can run or build from source, you can pick up the latest code from https://github.com/silnrsi/font-ttf/

More details:

You might have noticed that the `CFF` table is not in the list of supported tables given in [Font:TTF::Font](https://metacpan.org/pod/Font::TTF::Font).  In our usage we've never needed CFF font support, nor has anyone contributed such via a pull-request. Tables (like CFF) that Font::TTF doesn't know anything about will simply be copied verbatim to the output font. 

This should be sufficient in your use-case, but one thing was preventing it: the first four bytes of a font file are different for CFF-flavored fonts, and Font::TTF wasn't setting those bytes correctly. Commit e7d8f975 fixes that.

**Comment by bobh0303** [comment]
As far as I'm aware, no further action is needed.
