### ISSUE TITLE
usLastCharIndex with beyond-BMP Characters

### ISSUE THREAD

**Issue by ClintGoss** [silnrsi/font-ttf#11]
OS_2::update() sets usLastCharIndex to the highest mapped BMP code point. However, the spec stipulates:

> Fonts that support supplementary characters
> should set the value in this field to 0xFFFF.

**Comment by bobh0303** [comment]
And do you have supplementary chars in your font?

**Comment by bobh0303** [comment]
Hm. Yes, this looks problematic:
```
    $map = $self->{' PARENT'}{'cmap'}->find_ms || return undef;
    $hmtx = $self->{' PARENT'}{'hmtx'}->read;

    @keys = sort {$a <=> $b} grep {$_ < 0x10000} keys %{$map->{'val'}};

    $self->{'usFirstCharIndex'} = $keys[0];
    $self->{'usLastCharIndex'} = $keys[-1];
```

**Comment by bobh0303** [comment]
Can you try the code in the branch fix_OS2_lastCharIndex ?

**Comment by ClintGoss** [comment]
Yes, I tested this against a font with U+FFFD (Object Replacement) and a flock of glyphs mapped to the nose-bleed end of the SPUA-B (U+10FF01 and beyond). The code set OS2.usLastCharIndex to 0xFFFD rather than 0xFFFF, as a reading of the code would suggest ...

Actually, this opens an optimization: a linear search over keys %{$map->{'val'}} for a beyond-BMP code point, would (if such a code point is found) allow the code to set usLastCharIndex directly (to 0xFFFF) and avoid the sort on that array.

**Comment by ClintGoss** [comment]
> Can you try the code in the branch fix_OS2_lastCharIndex ?

Easiest way for me it so test this is to run it against my full pipeline. Results will be back in two days (next pipeline will start in 36 hours), but that should be a good test. I'll report back ...

I am still bothered by the sort() when a linear scan for min and max would suffice. Still, an O(n*log(n)) sort in C might be faster in many cases than a O(n) search in perl?

**Comment by bobh0303** [comment]
>Still, an O(n*log(n)) sort in C might be faster in many cases than a O(n) search in perl?

That is what I've generally understood, but profiling it would tell for sure. Feel free ;-)

Btw, there are potentially two pieces of info needed from the cmap: 
- Are there any codepoints > 0xFFFF ?
- If not, what is the maximum codepoint?

So in the case of BMP-only fonts a linear search will always be going through the entire list.

**Comment by bobh0303** [comment]
Fixed by f00d6e4d; test added in 0477f3fb

**Comment by ClintGoss** [comment]
This update passed all the related tests in my pipeline ...

**Comment by bobh0303** [comment]
Thanks for confirming.  I added a quick test (see `t/os2.t`) and confirmed it was working, then merged the branch to master yesterday.
